version: "3.0"

services:
  sensor-temperature-0:
    build: ./packages/sensor
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: temperature/0
      MQTT_PUB_INTERVAL: 20000
      VALUE_MIN: 40
      VALUE_MAX: 42

  sensor-temperature-1:
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: temperature/1
      MQTT_PUB_INTERVAL: 20000
      VALUE_MIN: 38
      VALUE_MAX: 40
    depends_on:
      - sensor-temperature-0

  sensor-temperature-2:
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: temperature/2
      MQTT_PUB_INTERVAL: 20000
      VALUE_MIN: 36
      VALUE_MAX: 38
    depends_on:
      - sensor-temperature-0

  sensor-weight-0:
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: weight-0
      MQTT_PUB_INTERVAL: 60000
      VALUE_MIN: 140
      VALUE_MAX: 142
    depends_on:
      - sensor-temperature-0

  sensor-weight-1:
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: weight-1
      MQTT_PUB_INTERVAL: 60000
      VALUE_MIN: 162
      VALUE_MAX: 166
    depends_on:
      - sensor-temperature-0

  sensor-weight-2:
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: weight-2
      MQTT_PUB_INTERVAL: 60000
      VALUE_MIN: 152
      VALUE_MAX: 156
    depends_on:
      - sensor-temperature-0
