version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./packages/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
