version: "3.0"

services:
  # Eclipse - Mosquitto MQTT server
  # https://hub.docker.com/_/eclipse-mosquitto
  mosquitto:
    ports:
      - "1883:1883"
      - "9001:9001"

  # MariaDB - Relational database
  # https://hub.docker.com/r/linuxserver/mariadb
  mariadb:
    ports:
      - "3306:3306"

  # InfluxDB - Time series database
  # https://hub.docker.com/_/influxdb
  influxdb:
    ports:
      - "8086:8086"
