version: "3.0"

services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./packages/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
