version: "3.0"

services:
  # Eclipse - Mosquitto MQTT server
  # https://hub.docker.com/_/eclipse-mosquitto
  mosquitto:
    image: eclipse-mosquitto:1.6
    container_name: mosquitto
    restart: always
    volumes:
      - ./packages/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # MariaDB - Relational database
  # https://hub.docker.com/r/linuxserver/mariadb
  mariadb:
    image: linuxserver/mariadb:110.4.10mariabionic-ls44
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_data:/config
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: project_admin
      MYSQL_PASSWORD: ${DB_PASSWORD}

  # InfluxDB - Time series database
  # https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    restart: always
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: root
      INFLUXDB_DB: project
      INFLUXDB_USER: project_admin
      INFLUXDB_USER_PASSWORD: ${DB_PASSWORD}

  # MQTT - InfluxDB Persister
  mqtt-influx-persister:
    build: ./packages/mqtt-influx-persister
    image: shevtsod/ense483-project-mqtt-influx-persister
    container_name: mqtt-influx-persister
    restart: always
    environment:
      MQTT_HOST: mosquitto
      INFLUX_HOST: influxdb
      INFLUX_DB: project
      INFLUX_USERNAME: project_admin
      INFLUX_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - influxdb

  # API
  api:
    build: ./packages/api
    image: shevtsod/ense483-project-api
    container_name: api
    restart: always
    ports:
      - "8081:8080"
    environment:
      HOST: api
      SECRET_KEY: ${SECRET_KEY}
      DB_HOST: mariadb
      DB_DB: project
      DB_USERNAME: project_admin
      DB_PASSWORD: ${DB_PASSWORD}
      INFLUX_HOST: influxdb
      INFLUX_DB: project
      INFLUX_USERNAME: project_admin
      INFLUX_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb
      - influxdb

volumes:
  mariadb_data:
  influxdb_data:
