version: "3.0"

services:
  # MariaDB - Relational database
  # https://hub.docker.com/_/mariadb
  mariadb:
    image: mariadb:10.1

  # Sensor
  # Start a few sensors for testing purposes
  # NOTE: Build image locally from repository
  sensor0:
    build: ./packages/sensor
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: temperature/0
      MQTT_PUB_INTERVAL: 20000
      VALUE_MIN: 40
      VALUE_MAX: 42

  sensor1:
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: temperature/1
      MQTT_PUB_INTERVAL: 20000
      VALUE_MIN: 38
      VALUE_MAX: 40
    depends_on:
      - sensor0

  sensor2:
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: weight/0
      MQTT_PUB_INTERVAL: 60000
      VALUE_MIN: 142
      VALUE_MAX: 144
    depends_on:
      - sensor0

  sensor3:
    image: shevtsod/ense483-project-sensor
    restart: always
    environment:
      MQTT_HOST: mosquitto
      MQTT_PUB_TOPIC: weight/1
      MQTT_PUB_INTERVAL: 60000
      VALUE_MIN: 130
      VALUE_MAX: 132
    depends_on:
      - sensor0
